CREATE TABLE Sales
(
[Id]			UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
[SaleDate]		DATETIME		 NOT NULL DEFAULT CURRENT_TIMESTAMP,
[Product_Id]	UNIQUEIDENTIFIER NOT NULL REFERENCES Products(Id),
[Quantity]		INT				 NOT NULL DEFAULT 1,
[Manager_Id]	UNIQUEIDENTIFIER NOT NULL REFERENCES Managers(Id),
[DeleteDt]		DATETIME		 NULL
);

